# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/165zw4g5VA6VJ3ixSQan7hpYdcuO9J-fI
"""

import numpy as np

#Here I am going to divide the given rectangular region into 27 parts(3x0.5 each).
#Then I am assigning the values 1 to 5 for the rectangular parts of the lake.
#And then assigning the values from -21 to 0 for the parts that are not inside the lake.
#Then I created an array of size 100000 whose elements are randomly from the integers -21,-20,...,3,4,5 using np.random.randint.
#The positive integers represent that the helicopter have crashed inside the lake.
#And the non-positive integers represent that the helicopter have crashed outside the lake.
#Then I calculated the number of positive integers in the array by running a loop.
#And finally calculated probability(=number of positive elements of the array/total number of elements of the array).
rand_var_arr=np.random.randint(-21,6,size=100000)
i=0
count=0
while i<100000:
  if rand_var_arr[i]>0:
    count=count+1
  i=i+1
print(f"{count/100000}")